[package]
name = "n-body"
version = "0.1.0"
authors = ["MysticPing <hajjvictor@live.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
